baseurl: https://yenngee-dataviz.netlify.app/
languageCode: en
defaultContentLanguage: en
title: Hugo Theme Dream
theme: hugo-theme-dream
params:
  author: Ng Yen Ngee
  avatar: /img/avatar.jpeg
  background: '#f7f7f7'
  email: g1enyy0ung@gmail.com
  headerTitle: Hugo Theme Dream
  linkColor: seagreen
  motto: Motto
  siteStartYear: 2016
